<?php
require('config/Config.php');
require('function/GlobalFunctions.php');
require('config/Autoload.php');
//////////
require('views/include/header.php');
//////////
require('views/form/index.php');
//////////
require('views/include/footer.php');
