<?php
// filter_var
// filter_input
// filter_list
/*
FILTER_VALIDATE_INT
FILTER_VALIDATE_BOOLEAN
FILTER_VALIDATE_FLOAT
FILTER_VALIDATE_URL
FILTER_VALIDATE_EMAIL
FILTER_VALIDATE_REGEX
FILTER_VALIDATE_IP

FILTER_SANITIZE_STRING
FILTER_SANITIZE_ENCODED
FILTER_SANITIZE_SPECIAL_CHARS
*/
